image: docker:stable

stages:
  - build
  - test


variables:
  IMAGE: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}

build:koko:
  stage: build
  services:
    - docker:dind

  variables:
    DOCKER_DRIVER: "overlay2"

  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE:koko || true
    - docker build
         --cache-from $IMAGE:koko
         --tag $IMAGE:koko
         --file ./Dockerfile
         "."
    - docker push $IMAGE:koko

test:koko:
  stage : test
  image : $IMAGE:koko
  services:
    - postgres:koko
  variables:
      POSTGRES_DB: "users"
      POSTGRES_USER: "runner"
      POSTGRES_PASSWORD: ""
      DATABASE_TEST_URL: "postgres://runner@postgres:5432/users"
  script:
    - cd /usr/src/app
    - pip install -r requirements.txt
    - python -m pytest "app/tests" -p no:warnings
    - python -m flake8 app
    - python -m black app --check

