version: '3.7'

services:
  koko:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ".:/usr/src/app"
    ports:
    - 5003:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@koko-db:5432/koko_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@koko-db:5432/koko_test
    depends_on:
      - koko-db

  koko-db:
    build:
      context: ./app/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  adminer:
    image: adminer
    container_name: naima_adminer
    ports:
      - "8080:8080"
    links:
      - "koko-db:db"
    depends_on:
      - "koko-db"
    networks:
      - "default"